// flow-typed signature: 151e5706c93beb8e50daede53f8fc263
// flow-typed version: <<STUB>>/babel-plugin-s2s-action-creater_v^0.3.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-s2s-action-creater'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-s2s-action-creater' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-s2s-action-creater/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-s2s-action-creater/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-action-creater/lib/index'>;
}
