// flow-typed signature: ab5d147d23966ffa9af595dd1bc6edd6
// flow-typed version: <<STUB>>/nivo_v^0.31.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nivo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nivo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nivo/es/components/axes/Axes' {
  declare module.exports: any;
}

declare module 'nivo/es/components/axes/Axis' {
  declare module.exports: any;
}

declare module 'nivo/es/components/axes/AxisTick' {
  declare module.exports: any;
}

declare module 'nivo/es/components/axes/Grid' {
  declare module.exports: any;
}

declare module 'nivo/es/components/axes/GridLine' {
  declare module.exports: any;
}

declare module 'nivo/es/components/axes/GridLines' {
  declare module.exports: any;
}

declare module 'nivo/es/components/axes/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/cartesian/markers/CartesianMarkers' {
  declare module.exports: any;
}

declare module 'nivo/es/components/cartesian/markers/CartesianMarkersItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/Bar' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/BarCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/BarItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/ResponsiveBar' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bar/ResponsiveBarCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/Bubble' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/BubbleCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/BubbleHtml' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/BubbleHtmlNode' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/BubbleNode' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/interactivity' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/motion' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/ResponsiveBubble' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/ResponsiveBubbleCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/bubble/ResponsiveBubbleHtml' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/Calendar' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/CalendarDay' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/CalendarMonthPath' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/calendar/ResponsiveCalendar' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/Chord' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ChordArcs' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ChordArcTooltip' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ChordCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ChordLabels' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ChordRibbons' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ResponsiveChord' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/chord/ResponsiveChordCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/Container' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/HeatMap' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/HeatMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/HeatMapCellCircle' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/HeatMapCellRect' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/HeatMapCellTooltip' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/ResponsiveHeatMap' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/heatmap/ResponsiveHeatMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/Line' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/LineAreas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/LineDots' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/LineLines' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/LineSlices' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/LineSlicesItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/line/ResponsiveLine' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/Pie' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/PieRadialLabels' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/PieSlicesLabels' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/pie/ResponsivePie' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/Radar' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarDots' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarGrid' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarGridLabels' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarGridLevels' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarShapes' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarTooltip' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/RadarTooltipItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/radar/ResponsiveRadar' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/ResponsiveWrapper' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/ResponsiveSankey' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/Sankey' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/SankeyLabels' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/SankeyLinks' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/SankeyLinksItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/SankeyNodes' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sankey/SankeyNodesItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/ResponsiveStream' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/Stream' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/StreamLayers' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/StreamSlices' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/stream/StreamSlicesItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sunburst/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sunburst/ResponsiveSunburst' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sunburst/Sunburst' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/sunburst/SunburstArc' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/SvgWrapper' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/interactivity' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/motion' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/ResponsiveTreeMap' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/ResponsiveTreeMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/ResponsiveTreeMapHtml' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/TreeMap' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/TreeMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/TreeMapHtml' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/TreeMapHtmlNode' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/TreeMapNode' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/treemap/TreeMapNodeTooltip' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/voronoi/enhance' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/voronoi/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/voronoi/props' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/voronoi/ResponsiveVoronoi' {
  declare module.exports: any;
}

declare module 'nivo/es/components/charts/voronoi/Voronoi' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/Defs' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/gradients/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/gradients/LinearGradient' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/patterns/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/patterns/PatternDots' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/patterns/PatternLines' {
  declare module.exports: any;
}

declare module 'nivo/es/components/defs/patterns/PatternSquares' {
  declare module.exports: any;
}

declare module 'nivo/es/components/dots/DotsItem' {
  declare module.exports: any;
}

declare module 'nivo/es/components/dots/DotsItemSymbol' {
  declare module.exports: any;
}

declare module 'nivo/es/components/dots/index' {
  declare module.exports: any;
}

declare module 'nivo/es/components/SmartMotion' {
  declare module.exports: any;
}

declare module 'nivo/es/components/tooltip/BasicTooltip' {
  declare module.exports: any;
}

declare module 'nivo/es/components/tooltip/Chip' {
  declare module.exports: any;
}

declare module 'nivo/es/components/tooltip/TableTooltip' {
  declare module.exports: any;
}

declare module 'nivo/es/constants/directions' {
  declare module.exports: any;
}

declare module 'nivo/es/constants/index' {
  declare module.exports: any;
}

declare module 'nivo/es/defaults/index' {
  declare module.exports: any;
}

declare module 'nivo/es/defaults/theme' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/index' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/withColors' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/withCurve' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/withDimensions' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/withHierarchy' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/withMotion' {
  declare module.exports: any;
}

declare module 'nivo/es/hocs/withTheme' {
  declare module.exports: any;
}

declare module 'nivo/es/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/axes' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/bridge' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/canvas/axes/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/canvas/charts/heatmap/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/bar/common' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/bar/grouped' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/bar/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/bar/stacked' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/bubble/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/calendar/CalendarLayout' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/heatmap/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/charts/line/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/colors/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/colors/inherit' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/colors/motion' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/colors/quantize' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/defs' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/hierarchy' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/interactivity/detect' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/interactivity/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/noop' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/polar/index' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/polar/labels' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/polar/utils' {
  declare module.exports: any;
}

declare module 'nivo/es/lib/propertiesConverters' {
  declare module.exports: any;
}

declare module 'nivo/es/props/colors' {
  declare module.exports: any;
}

declare module 'nivo/es/props/curve' {
  declare module.exports: any;
}

declare module 'nivo/es/props/defs' {
  declare module.exports: any;
}

declare module 'nivo/es/props/index' {
  declare module.exports: any;
}

declare module 'nivo/es/props/sankey' {
  declare module.exports: any;
}

declare module 'nivo/es/props/stack' {
  declare module.exports: any;
}

declare module 'nivo/es/props/treeMap' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/Axes' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/Axis' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/AxisTick' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/Grid' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/GridLine' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/GridLines' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/axes/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/cartesian/markers/CartesianMarkers' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/cartesian/markers/CartesianMarkersItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/Bar' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/BarCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/BarItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/ResponsiveBar' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bar/ResponsiveBarCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/Bubble' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/BubbleCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/BubbleHtml' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/BubbleHtmlNode' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/BubbleNode' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/interactivity' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/motion' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/ResponsiveBubble' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/ResponsiveBubbleCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/bubble/ResponsiveBubbleHtml' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/Calendar' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/CalendarDay' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/CalendarMonthPath' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/calendar/ResponsiveCalendar' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/Chord' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ChordArcs' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ChordArcTooltip' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ChordCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ChordLabels' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ChordRibbons' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ResponsiveChord' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/chord/ResponsiveChordCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/Container' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/HeatMap' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/HeatMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/HeatMapCellCircle' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/HeatMapCellRect' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/HeatMapCellTooltip' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/ResponsiveHeatMap' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/heatmap/ResponsiveHeatMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/Line' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/LineAreas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/LineDots' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/LineLines' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/LineSlices' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/LineSlicesItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/line/ResponsiveLine' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/Pie' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/PieRadialLabels' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/PieSlicesLabels' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/pie/ResponsivePie' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/Radar' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarDots' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarGrid' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarGridLabels' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarGridLevels' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarShapes' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarTooltip' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/RadarTooltipItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/radar/ResponsiveRadar' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/ResponsiveWrapper' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/ResponsiveSankey' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/Sankey' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/SankeyLabels' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/SankeyLinks' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/SankeyLinksItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/SankeyNodes' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sankey/SankeyNodesItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/ResponsiveStream' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/Stream' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/StreamLayers' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/StreamSlices' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/stream/StreamSlicesItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sunburst/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sunburst/ResponsiveSunburst' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sunburst/Sunburst' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/sunburst/SunburstArc' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/SvgWrapper' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/interactivity' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/motion' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/ResponsiveTreeMap' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/ResponsiveTreeMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/ResponsiveTreeMapHtml' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/TreeMap' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/TreeMapCanvas' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/TreeMapHtml' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/TreeMapHtmlNode' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/TreeMapNode' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/treemap/TreeMapNodeTooltip' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/voronoi/enhance' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/voronoi/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/voronoi/props' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/voronoi/ResponsiveVoronoi' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/charts/voronoi/Voronoi' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/Defs' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/gradients/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/gradients/LinearGradient' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/patterns/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/patterns/PatternDots' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/patterns/PatternLines' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/defs/patterns/PatternSquares' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/dots/DotsItem' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/dots/DotsItemSymbol' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/dots/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/SmartMotion' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/tooltip/BasicTooltip' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/tooltip/Chip' {
  declare module.exports: any;
}

declare module 'nivo/lib/components/tooltip/TableTooltip' {
  declare module.exports: any;
}

declare module 'nivo/lib/constants/directions' {
  declare module.exports: any;
}

declare module 'nivo/lib/constants/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/defaults/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/defaults/theme' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/withColors' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/withCurve' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/withDimensions' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/withHierarchy' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/withMotion' {
  declare module.exports: any;
}

declare module 'nivo/lib/hocs/withTheme' {
  declare module.exports: any;
}

declare module 'nivo/lib/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/axes' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/bridge' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/canvas/axes/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/canvas/charts/heatmap/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/bar/common' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/bar/grouped' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/bar/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/bar/stacked' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/bubble/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/calendar/CalendarLayout' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/heatmap/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/charts/line/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/colors/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/colors/inherit' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/colors/motion' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/colors/quantize' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/defs' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/hierarchy' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/interactivity/detect' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/interactivity/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/noop' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/polar/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/polar/labels' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/polar/utils' {
  declare module.exports: any;
}

declare module 'nivo/lib/lib/propertiesConverters' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/colors' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/curve' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/defs' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/index' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/sankey' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/stack' {
  declare module.exports: any;
}

declare module 'nivo/lib/props/treeMap' {
  declare module.exports: any;
}

declare module 'nivo/scripts/generate-changelog' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nivo/es/components/axes/Axes.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/Axes'>;
}
declare module 'nivo/es/components/axes/Axis.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/Axis'>;
}
declare module 'nivo/es/components/axes/AxisTick.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/AxisTick'>;
}
declare module 'nivo/es/components/axes/Grid.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/Grid'>;
}
declare module 'nivo/es/components/axes/GridLine.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/GridLine'>;
}
declare module 'nivo/es/components/axes/GridLines.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/GridLines'>;
}
declare module 'nivo/es/components/axes/index.js' {
  declare module.exports: $Exports<'nivo/es/components/axes/index'>;
}
declare module 'nivo/es/components/cartesian/markers/CartesianMarkers.js' {
  declare module.exports: $Exports<'nivo/es/components/cartesian/markers/CartesianMarkers'>;
}
declare module 'nivo/es/components/cartesian/markers/CartesianMarkersItem.js' {
  declare module.exports: $Exports<'nivo/es/components/cartesian/markers/CartesianMarkersItem'>;
}
declare module 'nivo/es/components/charts/bar/Bar.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/Bar'>;
}
declare module 'nivo/es/components/charts/bar/BarCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/BarCanvas'>;
}
declare module 'nivo/es/components/charts/bar/BarItem.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/BarItem'>;
}
declare module 'nivo/es/components/charts/bar/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/enhance'>;
}
declare module 'nivo/es/components/charts/bar/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/index'>;
}
declare module 'nivo/es/components/charts/bar/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/props'>;
}
declare module 'nivo/es/components/charts/bar/ResponsiveBar.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/ResponsiveBar'>;
}
declare module 'nivo/es/components/charts/bar/ResponsiveBarCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bar/ResponsiveBarCanvas'>;
}
declare module 'nivo/es/components/charts/bubble/Bubble.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/Bubble'>;
}
declare module 'nivo/es/components/charts/bubble/BubbleCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/BubbleCanvas'>;
}
declare module 'nivo/es/components/charts/bubble/BubbleHtml.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/BubbleHtml'>;
}
declare module 'nivo/es/components/charts/bubble/BubbleHtmlNode.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/BubbleHtmlNode'>;
}
declare module 'nivo/es/components/charts/bubble/BubbleNode.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/BubbleNode'>;
}
declare module 'nivo/es/components/charts/bubble/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/enhance'>;
}
declare module 'nivo/es/components/charts/bubble/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/index'>;
}
declare module 'nivo/es/components/charts/bubble/interactivity.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/interactivity'>;
}
declare module 'nivo/es/components/charts/bubble/motion.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/motion'>;
}
declare module 'nivo/es/components/charts/bubble/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/props'>;
}
declare module 'nivo/es/components/charts/bubble/ResponsiveBubble.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/ResponsiveBubble'>;
}
declare module 'nivo/es/components/charts/bubble/ResponsiveBubbleCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/ResponsiveBubbleCanvas'>;
}
declare module 'nivo/es/components/charts/bubble/ResponsiveBubbleHtml.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/bubble/ResponsiveBubbleHtml'>;
}
declare module 'nivo/es/components/charts/calendar/Calendar.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/Calendar'>;
}
declare module 'nivo/es/components/charts/calendar/CalendarDay.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/CalendarDay'>;
}
declare module 'nivo/es/components/charts/calendar/CalendarMonthPath.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/CalendarMonthPath'>;
}
declare module 'nivo/es/components/charts/calendar/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/enhance'>;
}
declare module 'nivo/es/components/charts/calendar/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/index'>;
}
declare module 'nivo/es/components/charts/calendar/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/props'>;
}
declare module 'nivo/es/components/charts/calendar/ResponsiveCalendar.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/calendar/ResponsiveCalendar'>;
}
declare module 'nivo/es/components/charts/chord/Chord.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/Chord'>;
}
declare module 'nivo/es/components/charts/chord/ChordArcs.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ChordArcs'>;
}
declare module 'nivo/es/components/charts/chord/ChordArcTooltip.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ChordArcTooltip'>;
}
declare module 'nivo/es/components/charts/chord/ChordCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ChordCanvas'>;
}
declare module 'nivo/es/components/charts/chord/ChordLabels.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ChordLabels'>;
}
declare module 'nivo/es/components/charts/chord/ChordRibbons.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ChordRibbons'>;
}
declare module 'nivo/es/components/charts/chord/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/enhance'>;
}
declare module 'nivo/es/components/charts/chord/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/index'>;
}
declare module 'nivo/es/components/charts/chord/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/props'>;
}
declare module 'nivo/es/components/charts/chord/ResponsiveChord.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ResponsiveChord'>;
}
declare module 'nivo/es/components/charts/chord/ResponsiveChordCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/chord/ResponsiveChordCanvas'>;
}
declare module 'nivo/es/components/charts/Container.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/Container'>;
}
declare module 'nivo/es/components/charts/heatmap/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/enhance'>;
}
declare module 'nivo/es/components/charts/heatmap/HeatMap.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/HeatMap'>;
}
declare module 'nivo/es/components/charts/heatmap/HeatMapCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/HeatMapCanvas'>;
}
declare module 'nivo/es/components/charts/heatmap/HeatMapCellCircle.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/HeatMapCellCircle'>;
}
declare module 'nivo/es/components/charts/heatmap/HeatMapCellRect.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/HeatMapCellRect'>;
}
declare module 'nivo/es/components/charts/heatmap/HeatMapCellTooltip.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/HeatMapCellTooltip'>;
}
declare module 'nivo/es/components/charts/heatmap/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/index'>;
}
declare module 'nivo/es/components/charts/heatmap/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/props'>;
}
declare module 'nivo/es/components/charts/heatmap/ResponsiveHeatMap.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/ResponsiveHeatMap'>;
}
declare module 'nivo/es/components/charts/heatmap/ResponsiveHeatMapCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/heatmap/ResponsiveHeatMapCanvas'>;
}
declare module 'nivo/es/components/charts/line/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/index'>;
}
declare module 'nivo/es/components/charts/line/Line.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/Line'>;
}
declare module 'nivo/es/components/charts/line/LineAreas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/LineAreas'>;
}
declare module 'nivo/es/components/charts/line/LineDots.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/LineDots'>;
}
declare module 'nivo/es/components/charts/line/LineLines.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/LineLines'>;
}
declare module 'nivo/es/components/charts/line/LineSlices.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/LineSlices'>;
}
declare module 'nivo/es/components/charts/line/LineSlicesItem.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/LineSlicesItem'>;
}
declare module 'nivo/es/components/charts/line/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/props'>;
}
declare module 'nivo/es/components/charts/line/ResponsiveLine.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/line/ResponsiveLine'>;
}
declare module 'nivo/es/components/charts/pie/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/enhance'>;
}
declare module 'nivo/es/components/charts/pie/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/index'>;
}
declare module 'nivo/es/components/charts/pie/Pie.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/Pie'>;
}
declare module 'nivo/es/components/charts/pie/PieRadialLabels.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/PieRadialLabels'>;
}
declare module 'nivo/es/components/charts/pie/PieSlicesLabels.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/PieSlicesLabels'>;
}
declare module 'nivo/es/components/charts/pie/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/props'>;
}
declare module 'nivo/es/components/charts/pie/ResponsivePie.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/pie/ResponsivePie'>;
}
declare module 'nivo/es/components/charts/radar/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/index'>;
}
declare module 'nivo/es/components/charts/radar/Radar.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/Radar'>;
}
declare module 'nivo/es/components/charts/radar/RadarDots.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarDots'>;
}
declare module 'nivo/es/components/charts/radar/RadarGrid.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarGrid'>;
}
declare module 'nivo/es/components/charts/radar/RadarGridLabels.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarGridLabels'>;
}
declare module 'nivo/es/components/charts/radar/RadarGridLevels.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarGridLevels'>;
}
declare module 'nivo/es/components/charts/radar/RadarShapes.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarShapes'>;
}
declare module 'nivo/es/components/charts/radar/RadarTooltip.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarTooltip'>;
}
declare module 'nivo/es/components/charts/radar/RadarTooltipItem.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/RadarTooltipItem'>;
}
declare module 'nivo/es/components/charts/radar/ResponsiveRadar.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/radar/ResponsiveRadar'>;
}
declare module 'nivo/es/components/charts/ResponsiveWrapper.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/ResponsiveWrapper'>;
}
declare module 'nivo/es/components/charts/sankey/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/enhance'>;
}
declare module 'nivo/es/components/charts/sankey/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/index'>;
}
declare module 'nivo/es/components/charts/sankey/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/props'>;
}
declare module 'nivo/es/components/charts/sankey/ResponsiveSankey.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/ResponsiveSankey'>;
}
declare module 'nivo/es/components/charts/sankey/Sankey.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/Sankey'>;
}
declare module 'nivo/es/components/charts/sankey/SankeyLabels.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/SankeyLabels'>;
}
declare module 'nivo/es/components/charts/sankey/SankeyLinks.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/SankeyLinks'>;
}
declare module 'nivo/es/components/charts/sankey/SankeyLinksItem.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/SankeyLinksItem'>;
}
declare module 'nivo/es/components/charts/sankey/SankeyNodes.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/SankeyNodes'>;
}
declare module 'nivo/es/components/charts/sankey/SankeyNodesItem.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sankey/SankeyNodesItem'>;
}
declare module 'nivo/es/components/charts/stream/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/enhance'>;
}
declare module 'nivo/es/components/charts/stream/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/index'>;
}
declare module 'nivo/es/components/charts/stream/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/props'>;
}
declare module 'nivo/es/components/charts/stream/ResponsiveStream.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/ResponsiveStream'>;
}
declare module 'nivo/es/components/charts/stream/Stream.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/Stream'>;
}
declare module 'nivo/es/components/charts/stream/StreamLayers.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/StreamLayers'>;
}
declare module 'nivo/es/components/charts/stream/StreamSlices.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/StreamSlices'>;
}
declare module 'nivo/es/components/charts/stream/StreamSlicesItem.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/stream/StreamSlicesItem'>;
}
declare module 'nivo/es/components/charts/sunburst/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sunburst/index'>;
}
declare module 'nivo/es/components/charts/sunburst/ResponsiveSunburst.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sunburst/ResponsiveSunburst'>;
}
declare module 'nivo/es/components/charts/sunburst/Sunburst.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sunburst/Sunburst'>;
}
declare module 'nivo/es/components/charts/sunburst/SunburstArc.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/sunburst/SunburstArc'>;
}
declare module 'nivo/es/components/charts/SvgWrapper.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/SvgWrapper'>;
}
declare module 'nivo/es/components/charts/treemap/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/enhance'>;
}
declare module 'nivo/es/components/charts/treemap/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/index'>;
}
declare module 'nivo/es/components/charts/treemap/interactivity.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/interactivity'>;
}
declare module 'nivo/es/components/charts/treemap/motion.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/motion'>;
}
declare module 'nivo/es/components/charts/treemap/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/props'>;
}
declare module 'nivo/es/components/charts/treemap/ResponsiveTreeMap.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/ResponsiveTreeMap'>;
}
declare module 'nivo/es/components/charts/treemap/ResponsiveTreeMapCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/ResponsiveTreeMapCanvas'>;
}
declare module 'nivo/es/components/charts/treemap/ResponsiveTreeMapHtml.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/ResponsiveTreeMapHtml'>;
}
declare module 'nivo/es/components/charts/treemap/TreeMap.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/TreeMap'>;
}
declare module 'nivo/es/components/charts/treemap/TreeMapCanvas.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/TreeMapCanvas'>;
}
declare module 'nivo/es/components/charts/treemap/TreeMapHtml.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/TreeMapHtml'>;
}
declare module 'nivo/es/components/charts/treemap/TreeMapHtmlNode.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/TreeMapHtmlNode'>;
}
declare module 'nivo/es/components/charts/treemap/TreeMapNode.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/TreeMapNode'>;
}
declare module 'nivo/es/components/charts/treemap/TreeMapNodeTooltip.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/treemap/TreeMapNodeTooltip'>;
}
declare module 'nivo/es/components/charts/voronoi/enhance.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/voronoi/enhance'>;
}
declare module 'nivo/es/components/charts/voronoi/index.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/voronoi/index'>;
}
declare module 'nivo/es/components/charts/voronoi/props.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/voronoi/props'>;
}
declare module 'nivo/es/components/charts/voronoi/ResponsiveVoronoi.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/voronoi/ResponsiveVoronoi'>;
}
declare module 'nivo/es/components/charts/voronoi/Voronoi.js' {
  declare module.exports: $Exports<'nivo/es/components/charts/voronoi/Voronoi'>;
}
declare module 'nivo/es/components/defs/Defs.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/Defs'>;
}
declare module 'nivo/es/components/defs/gradients/index.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/gradients/index'>;
}
declare module 'nivo/es/components/defs/gradients/LinearGradient.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/gradients/LinearGradient'>;
}
declare module 'nivo/es/components/defs/index.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/index'>;
}
declare module 'nivo/es/components/defs/patterns/index.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/patterns/index'>;
}
declare module 'nivo/es/components/defs/patterns/PatternDots.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/patterns/PatternDots'>;
}
declare module 'nivo/es/components/defs/patterns/PatternLines.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/patterns/PatternLines'>;
}
declare module 'nivo/es/components/defs/patterns/PatternSquares.js' {
  declare module.exports: $Exports<'nivo/es/components/defs/patterns/PatternSquares'>;
}
declare module 'nivo/es/components/dots/DotsItem.js' {
  declare module.exports: $Exports<'nivo/es/components/dots/DotsItem'>;
}
declare module 'nivo/es/components/dots/DotsItemSymbol.js' {
  declare module.exports: $Exports<'nivo/es/components/dots/DotsItemSymbol'>;
}
declare module 'nivo/es/components/dots/index.js' {
  declare module.exports: $Exports<'nivo/es/components/dots/index'>;
}
declare module 'nivo/es/components/SmartMotion.js' {
  declare module.exports: $Exports<'nivo/es/components/SmartMotion'>;
}
declare module 'nivo/es/components/tooltip/BasicTooltip.js' {
  declare module.exports: $Exports<'nivo/es/components/tooltip/BasicTooltip'>;
}
declare module 'nivo/es/components/tooltip/Chip.js' {
  declare module.exports: $Exports<'nivo/es/components/tooltip/Chip'>;
}
declare module 'nivo/es/components/tooltip/TableTooltip.js' {
  declare module.exports: $Exports<'nivo/es/components/tooltip/TableTooltip'>;
}
declare module 'nivo/es/constants/directions.js' {
  declare module.exports: $Exports<'nivo/es/constants/directions'>;
}
declare module 'nivo/es/constants/index.js' {
  declare module.exports: $Exports<'nivo/es/constants/index'>;
}
declare module 'nivo/es/defaults/index.js' {
  declare module.exports: $Exports<'nivo/es/defaults/index'>;
}
declare module 'nivo/es/defaults/theme.js' {
  declare module.exports: $Exports<'nivo/es/defaults/theme'>;
}
declare module 'nivo/es/hocs/index.js' {
  declare module.exports: $Exports<'nivo/es/hocs/index'>;
}
declare module 'nivo/es/hocs/withColors.js' {
  declare module.exports: $Exports<'nivo/es/hocs/withColors'>;
}
declare module 'nivo/es/hocs/withCurve.js' {
  declare module.exports: $Exports<'nivo/es/hocs/withCurve'>;
}
declare module 'nivo/es/hocs/withDimensions.js' {
  declare module.exports: $Exports<'nivo/es/hocs/withDimensions'>;
}
declare module 'nivo/es/hocs/withHierarchy.js' {
  declare module.exports: $Exports<'nivo/es/hocs/withHierarchy'>;
}
declare module 'nivo/es/hocs/withMotion.js' {
  declare module.exports: $Exports<'nivo/es/hocs/withMotion'>;
}
declare module 'nivo/es/hocs/withTheme.js' {
  declare module.exports: $Exports<'nivo/es/hocs/withTheme'>;
}
declare module 'nivo/es/index.js' {
  declare module.exports: $Exports<'nivo/es/index'>;
}
declare module 'nivo/es/lib/axes.js' {
  declare module.exports: $Exports<'nivo/es/lib/axes'>;
}
declare module 'nivo/es/lib/bridge.js' {
  declare module.exports: $Exports<'nivo/es/lib/bridge'>;
}
declare module 'nivo/es/lib/canvas/axes/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/canvas/axes/index'>;
}
declare module 'nivo/es/lib/canvas/charts/heatmap/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/canvas/charts/heatmap/index'>;
}
declare module 'nivo/es/lib/charts/bar/common.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/bar/common'>;
}
declare module 'nivo/es/lib/charts/bar/grouped.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/bar/grouped'>;
}
declare module 'nivo/es/lib/charts/bar/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/bar/index'>;
}
declare module 'nivo/es/lib/charts/bar/stacked.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/bar/stacked'>;
}
declare module 'nivo/es/lib/charts/bubble/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/bubble/index'>;
}
declare module 'nivo/es/lib/charts/calendar/CalendarLayout.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/calendar/CalendarLayout'>;
}
declare module 'nivo/es/lib/charts/heatmap/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/heatmap/index'>;
}
declare module 'nivo/es/lib/charts/line/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/charts/line/index'>;
}
declare module 'nivo/es/lib/colors/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/colors/index'>;
}
declare module 'nivo/es/lib/colors/inherit.js' {
  declare module.exports: $Exports<'nivo/es/lib/colors/inherit'>;
}
declare module 'nivo/es/lib/colors/motion.js' {
  declare module.exports: $Exports<'nivo/es/lib/colors/motion'>;
}
declare module 'nivo/es/lib/colors/quantize.js' {
  declare module.exports: $Exports<'nivo/es/lib/colors/quantize'>;
}
declare module 'nivo/es/lib/defs.js' {
  declare module.exports: $Exports<'nivo/es/lib/defs'>;
}
declare module 'nivo/es/lib/hierarchy.js' {
  declare module.exports: $Exports<'nivo/es/lib/hierarchy'>;
}
declare module 'nivo/es/lib/interactivity/detect.js' {
  declare module.exports: $Exports<'nivo/es/lib/interactivity/detect'>;
}
declare module 'nivo/es/lib/interactivity/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/interactivity/index'>;
}
declare module 'nivo/es/lib/noop.js' {
  declare module.exports: $Exports<'nivo/es/lib/noop'>;
}
declare module 'nivo/es/lib/polar/index.js' {
  declare module.exports: $Exports<'nivo/es/lib/polar/index'>;
}
declare module 'nivo/es/lib/polar/labels.js' {
  declare module.exports: $Exports<'nivo/es/lib/polar/labels'>;
}
declare module 'nivo/es/lib/polar/utils.js' {
  declare module.exports: $Exports<'nivo/es/lib/polar/utils'>;
}
declare module 'nivo/es/lib/propertiesConverters.js' {
  declare module.exports: $Exports<'nivo/es/lib/propertiesConverters'>;
}
declare module 'nivo/es/props/colors.js' {
  declare module.exports: $Exports<'nivo/es/props/colors'>;
}
declare module 'nivo/es/props/curve.js' {
  declare module.exports: $Exports<'nivo/es/props/curve'>;
}
declare module 'nivo/es/props/defs.js' {
  declare module.exports: $Exports<'nivo/es/props/defs'>;
}
declare module 'nivo/es/props/index.js' {
  declare module.exports: $Exports<'nivo/es/props/index'>;
}
declare module 'nivo/es/props/sankey.js' {
  declare module.exports: $Exports<'nivo/es/props/sankey'>;
}
declare module 'nivo/es/props/stack.js' {
  declare module.exports: $Exports<'nivo/es/props/stack'>;
}
declare module 'nivo/es/props/treeMap.js' {
  declare module.exports: $Exports<'nivo/es/props/treeMap'>;
}
declare module 'nivo/lib/components/axes/Axes.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/Axes'>;
}
declare module 'nivo/lib/components/axes/Axis.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/Axis'>;
}
declare module 'nivo/lib/components/axes/AxisTick.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/AxisTick'>;
}
declare module 'nivo/lib/components/axes/Grid.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/Grid'>;
}
declare module 'nivo/lib/components/axes/GridLine.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/GridLine'>;
}
declare module 'nivo/lib/components/axes/GridLines.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/GridLines'>;
}
declare module 'nivo/lib/components/axes/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/axes/index'>;
}
declare module 'nivo/lib/components/cartesian/markers/CartesianMarkers.js' {
  declare module.exports: $Exports<'nivo/lib/components/cartesian/markers/CartesianMarkers'>;
}
declare module 'nivo/lib/components/cartesian/markers/CartesianMarkersItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/cartesian/markers/CartesianMarkersItem'>;
}
declare module 'nivo/lib/components/charts/bar/Bar.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/Bar'>;
}
declare module 'nivo/lib/components/charts/bar/BarCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/BarCanvas'>;
}
declare module 'nivo/lib/components/charts/bar/BarItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/BarItem'>;
}
declare module 'nivo/lib/components/charts/bar/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/enhance'>;
}
declare module 'nivo/lib/components/charts/bar/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/index'>;
}
declare module 'nivo/lib/components/charts/bar/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/props'>;
}
declare module 'nivo/lib/components/charts/bar/ResponsiveBar.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/ResponsiveBar'>;
}
declare module 'nivo/lib/components/charts/bar/ResponsiveBarCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bar/ResponsiveBarCanvas'>;
}
declare module 'nivo/lib/components/charts/bubble/Bubble.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/Bubble'>;
}
declare module 'nivo/lib/components/charts/bubble/BubbleCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/BubbleCanvas'>;
}
declare module 'nivo/lib/components/charts/bubble/BubbleHtml.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/BubbleHtml'>;
}
declare module 'nivo/lib/components/charts/bubble/BubbleHtmlNode.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/BubbleHtmlNode'>;
}
declare module 'nivo/lib/components/charts/bubble/BubbleNode.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/BubbleNode'>;
}
declare module 'nivo/lib/components/charts/bubble/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/enhance'>;
}
declare module 'nivo/lib/components/charts/bubble/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/index'>;
}
declare module 'nivo/lib/components/charts/bubble/interactivity.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/interactivity'>;
}
declare module 'nivo/lib/components/charts/bubble/motion.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/motion'>;
}
declare module 'nivo/lib/components/charts/bubble/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/props'>;
}
declare module 'nivo/lib/components/charts/bubble/ResponsiveBubble.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/ResponsiveBubble'>;
}
declare module 'nivo/lib/components/charts/bubble/ResponsiveBubbleCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/ResponsiveBubbleCanvas'>;
}
declare module 'nivo/lib/components/charts/bubble/ResponsiveBubbleHtml.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/bubble/ResponsiveBubbleHtml'>;
}
declare module 'nivo/lib/components/charts/calendar/Calendar.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/Calendar'>;
}
declare module 'nivo/lib/components/charts/calendar/CalendarDay.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/CalendarDay'>;
}
declare module 'nivo/lib/components/charts/calendar/CalendarMonthPath.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/CalendarMonthPath'>;
}
declare module 'nivo/lib/components/charts/calendar/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/enhance'>;
}
declare module 'nivo/lib/components/charts/calendar/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/index'>;
}
declare module 'nivo/lib/components/charts/calendar/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/props'>;
}
declare module 'nivo/lib/components/charts/calendar/ResponsiveCalendar.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/calendar/ResponsiveCalendar'>;
}
declare module 'nivo/lib/components/charts/chord/Chord.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/Chord'>;
}
declare module 'nivo/lib/components/charts/chord/ChordArcs.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ChordArcs'>;
}
declare module 'nivo/lib/components/charts/chord/ChordArcTooltip.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ChordArcTooltip'>;
}
declare module 'nivo/lib/components/charts/chord/ChordCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ChordCanvas'>;
}
declare module 'nivo/lib/components/charts/chord/ChordLabels.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ChordLabels'>;
}
declare module 'nivo/lib/components/charts/chord/ChordRibbons.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ChordRibbons'>;
}
declare module 'nivo/lib/components/charts/chord/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/enhance'>;
}
declare module 'nivo/lib/components/charts/chord/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/index'>;
}
declare module 'nivo/lib/components/charts/chord/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/props'>;
}
declare module 'nivo/lib/components/charts/chord/ResponsiveChord.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ResponsiveChord'>;
}
declare module 'nivo/lib/components/charts/chord/ResponsiveChordCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/chord/ResponsiveChordCanvas'>;
}
declare module 'nivo/lib/components/charts/Container.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/Container'>;
}
declare module 'nivo/lib/components/charts/heatmap/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/enhance'>;
}
declare module 'nivo/lib/components/charts/heatmap/HeatMap.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/HeatMap'>;
}
declare module 'nivo/lib/components/charts/heatmap/HeatMapCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/HeatMapCanvas'>;
}
declare module 'nivo/lib/components/charts/heatmap/HeatMapCellCircle.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/HeatMapCellCircle'>;
}
declare module 'nivo/lib/components/charts/heatmap/HeatMapCellRect.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/HeatMapCellRect'>;
}
declare module 'nivo/lib/components/charts/heatmap/HeatMapCellTooltip.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/HeatMapCellTooltip'>;
}
declare module 'nivo/lib/components/charts/heatmap/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/index'>;
}
declare module 'nivo/lib/components/charts/heatmap/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/props'>;
}
declare module 'nivo/lib/components/charts/heatmap/ResponsiveHeatMap.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/ResponsiveHeatMap'>;
}
declare module 'nivo/lib/components/charts/heatmap/ResponsiveHeatMapCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/heatmap/ResponsiveHeatMapCanvas'>;
}
declare module 'nivo/lib/components/charts/line/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/index'>;
}
declare module 'nivo/lib/components/charts/line/Line.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/Line'>;
}
declare module 'nivo/lib/components/charts/line/LineAreas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/LineAreas'>;
}
declare module 'nivo/lib/components/charts/line/LineDots.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/LineDots'>;
}
declare module 'nivo/lib/components/charts/line/LineLines.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/LineLines'>;
}
declare module 'nivo/lib/components/charts/line/LineSlices.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/LineSlices'>;
}
declare module 'nivo/lib/components/charts/line/LineSlicesItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/LineSlicesItem'>;
}
declare module 'nivo/lib/components/charts/line/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/props'>;
}
declare module 'nivo/lib/components/charts/line/ResponsiveLine.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/line/ResponsiveLine'>;
}
declare module 'nivo/lib/components/charts/pie/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/enhance'>;
}
declare module 'nivo/lib/components/charts/pie/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/index'>;
}
declare module 'nivo/lib/components/charts/pie/Pie.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/Pie'>;
}
declare module 'nivo/lib/components/charts/pie/PieRadialLabels.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/PieRadialLabels'>;
}
declare module 'nivo/lib/components/charts/pie/PieSlicesLabels.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/PieSlicesLabels'>;
}
declare module 'nivo/lib/components/charts/pie/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/props'>;
}
declare module 'nivo/lib/components/charts/pie/ResponsivePie.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/pie/ResponsivePie'>;
}
declare module 'nivo/lib/components/charts/radar/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/index'>;
}
declare module 'nivo/lib/components/charts/radar/Radar.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/Radar'>;
}
declare module 'nivo/lib/components/charts/radar/RadarDots.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarDots'>;
}
declare module 'nivo/lib/components/charts/radar/RadarGrid.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarGrid'>;
}
declare module 'nivo/lib/components/charts/radar/RadarGridLabels.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarGridLabels'>;
}
declare module 'nivo/lib/components/charts/radar/RadarGridLevels.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarGridLevels'>;
}
declare module 'nivo/lib/components/charts/radar/RadarShapes.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarShapes'>;
}
declare module 'nivo/lib/components/charts/radar/RadarTooltip.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarTooltip'>;
}
declare module 'nivo/lib/components/charts/radar/RadarTooltipItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/RadarTooltipItem'>;
}
declare module 'nivo/lib/components/charts/radar/ResponsiveRadar.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/radar/ResponsiveRadar'>;
}
declare module 'nivo/lib/components/charts/ResponsiveWrapper.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/ResponsiveWrapper'>;
}
declare module 'nivo/lib/components/charts/sankey/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/enhance'>;
}
declare module 'nivo/lib/components/charts/sankey/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/index'>;
}
declare module 'nivo/lib/components/charts/sankey/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/props'>;
}
declare module 'nivo/lib/components/charts/sankey/ResponsiveSankey.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/ResponsiveSankey'>;
}
declare module 'nivo/lib/components/charts/sankey/Sankey.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/Sankey'>;
}
declare module 'nivo/lib/components/charts/sankey/SankeyLabels.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/SankeyLabels'>;
}
declare module 'nivo/lib/components/charts/sankey/SankeyLinks.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/SankeyLinks'>;
}
declare module 'nivo/lib/components/charts/sankey/SankeyLinksItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/SankeyLinksItem'>;
}
declare module 'nivo/lib/components/charts/sankey/SankeyNodes.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/SankeyNodes'>;
}
declare module 'nivo/lib/components/charts/sankey/SankeyNodesItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sankey/SankeyNodesItem'>;
}
declare module 'nivo/lib/components/charts/stream/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/enhance'>;
}
declare module 'nivo/lib/components/charts/stream/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/index'>;
}
declare module 'nivo/lib/components/charts/stream/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/props'>;
}
declare module 'nivo/lib/components/charts/stream/ResponsiveStream.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/ResponsiveStream'>;
}
declare module 'nivo/lib/components/charts/stream/Stream.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/Stream'>;
}
declare module 'nivo/lib/components/charts/stream/StreamLayers.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/StreamLayers'>;
}
declare module 'nivo/lib/components/charts/stream/StreamSlices.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/StreamSlices'>;
}
declare module 'nivo/lib/components/charts/stream/StreamSlicesItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/stream/StreamSlicesItem'>;
}
declare module 'nivo/lib/components/charts/sunburst/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sunburst/index'>;
}
declare module 'nivo/lib/components/charts/sunburst/ResponsiveSunburst.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sunburst/ResponsiveSunburst'>;
}
declare module 'nivo/lib/components/charts/sunburst/Sunburst.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sunburst/Sunburst'>;
}
declare module 'nivo/lib/components/charts/sunburst/SunburstArc.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/sunburst/SunburstArc'>;
}
declare module 'nivo/lib/components/charts/SvgWrapper.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/SvgWrapper'>;
}
declare module 'nivo/lib/components/charts/treemap/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/enhance'>;
}
declare module 'nivo/lib/components/charts/treemap/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/index'>;
}
declare module 'nivo/lib/components/charts/treemap/interactivity.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/interactivity'>;
}
declare module 'nivo/lib/components/charts/treemap/motion.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/motion'>;
}
declare module 'nivo/lib/components/charts/treemap/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/props'>;
}
declare module 'nivo/lib/components/charts/treemap/ResponsiveTreeMap.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/ResponsiveTreeMap'>;
}
declare module 'nivo/lib/components/charts/treemap/ResponsiveTreeMapCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/ResponsiveTreeMapCanvas'>;
}
declare module 'nivo/lib/components/charts/treemap/ResponsiveTreeMapHtml.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/ResponsiveTreeMapHtml'>;
}
declare module 'nivo/lib/components/charts/treemap/TreeMap.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/TreeMap'>;
}
declare module 'nivo/lib/components/charts/treemap/TreeMapCanvas.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/TreeMapCanvas'>;
}
declare module 'nivo/lib/components/charts/treemap/TreeMapHtml.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/TreeMapHtml'>;
}
declare module 'nivo/lib/components/charts/treemap/TreeMapHtmlNode.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/TreeMapHtmlNode'>;
}
declare module 'nivo/lib/components/charts/treemap/TreeMapNode.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/TreeMapNode'>;
}
declare module 'nivo/lib/components/charts/treemap/TreeMapNodeTooltip.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/treemap/TreeMapNodeTooltip'>;
}
declare module 'nivo/lib/components/charts/voronoi/enhance.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/voronoi/enhance'>;
}
declare module 'nivo/lib/components/charts/voronoi/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/voronoi/index'>;
}
declare module 'nivo/lib/components/charts/voronoi/props.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/voronoi/props'>;
}
declare module 'nivo/lib/components/charts/voronoi/ResponsiveVoronoi.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/voronoi/ResponsiveVoronoi'>;
}
declare module 'nivo/lib/components/charts/voronoi/Voronoi.js' {
  declare module.exports: $Exports<'nivo/lib/components/charts/voronoi/Voronoi'>;
}
declare module 'nivo/lib/components/defs/Defs.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/Defs'>;
}
declare module 'nivo/lib/components/defs/gradients/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/gradients/index'>;
}
declare module 'nivo/lib/components/defs/gradients/LinearGradient.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/gradients/LinearGradient'>;
}
declare module 'nivo/lib/components/defs/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/index'>;
}
declare module 'nivo/lib/components/defs/patterns/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/patterns/index'>;
}
declare module 'nivo/lib/components/defs/patterns/PatternDots.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/patterns/PatternDots'>;
}
declare module 'nivo/lib/components/defs/patterns/PatternLines.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/patterns/PatternLines'>;
}
declare module 'nivo/lib/components/defs/patterns/PatternSquares.js' {
  declare module.exports: $Exports<'nivo/lib/components/defs/patterns/PatternSquares'>;
}
declare module 'nivo/lib/components/dots/DotsItem.js' {
  declare module.exports: $Exports<'nivo/lib/components/dots/DotsItem'>;
}
declare module 'nivo/lib/components/dots/DotsItemSymbol.js' {
  declare module.exports: $Exports<'nivo/lib/components/dots/DotsItemSymbol'>;
}
declare module 'nivo/lib/components/dots/index.js' {
  declare module.exports: $Exports<'nivo/lib/components/dots/index'>;
}
declare module 'nivo/lib/components/SmartMotion.js' {
  declare module.exports: $Exports<'nivo/lib/components/SmartMotion'>;
}
declare module 'nivo/lib/components/tooltip/BasicTooltip.js' {
  declare module.exports: $Exports<'nivo/lib/components/tooltip/BasicTooltip'>;
}
declare module 'nivo/lib/components/tooltip/Chip.js' {
  declare module.exports: $Exports<'nivo/lib/components/tooltip/Chip'>;
}
declare module 'nivo/lib/components/tooltip/TableTooltip.js' {
  declare module.exports: $Exports<'nivo/lib/components/tooltip/TableTooltip'>;
}
declare module 'nivo/lib/constants/directions.js' {
  declare module.exports: $Exports<'nivo/lib/constants/directions'>;
}
declare module 'nivo/lib/constants/index.js' {
  declare module.exports: $Exports<'nivo/lib/constants/index'>;
}
declare module 'nivo/lib/defaults/index.js' {
  declare module.exports: $Exports<'nivo/lib/defaults/index'>;
}
declare module 'nivo/lib/defaults/theme.js' {
  declare module.exports: $Exports<'nivo/lib/defaults/theme'>;
}
declare module 'nivo/lib/hocs/index.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/index'>;
}
declare module 'nivo/lib/hocs/withColors.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/withColors'>;
}
declare module 'nivo/lib/hocs/withCurve.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/withCurve'>;
}
declare module 'nivo/lib/hocs/withDimensions.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/withDimensions'>;
}
declare module 'nivo/lib/hocs/withHierarchy.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/withHierarchy'>;
}
declare module 'nivo/lib/hocs/withMotion.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/withMotion'>;
}
declare module 'nivo/lib/hocs/withTheme.js' {
  declare module.exports: $Exports<'nivo/lib/hocs/withTheme'>;
}
declare module 'nivo/lib/index.js' {
  declare module.exports: $Exports<'nivo/lib/index'>;
}
declare module 'nivo/lib/lib/axes.js' {
  declare module.exports: $Exports<'nivo/lib/lib/axes'>;
}
declare module 'nivo/lib/lib/bridge.js' {
  declare module.exports: $Exports<'nivo/lib/lib/bridge'>;
}
declare module 'nivo/lib/lib/canvas/axes/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/canvas/axes/index'>;
}
declare module 'nivo/lib/lib/canvas/charts/heatmap/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/canvas/charts/heatmap/index'>;
}
declare module 'nivo/lib/lib/charts/bar/common.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/bar/common'>;
}
declare module 'nivo/lib/lib/charts/bar/grouped.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/bar/grouped'>;
}
declare module 'nivo/lib/lib/charts/bar/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/bar/index'>;
}
declare module 'nivo/lib/lib/charts/bar/stacked.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/bar/stacked'>;
}
declare module 'nivo/lib/lib/charts/bubble/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/bubble/index'>;
}
declare module 'nivo/lib/lib/charts/calendar/CalendarLayout.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/calendar/CalendarLayout'>;
}
declare module 'nivo/lib/lib/charts/heatmap/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/heatmap/index'>;
}
declare module 'nivo/lib/lib/charts/line/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/charts/line/index'>;
}
declare module 'nivo/lib/lib/colors/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/colors/index'>;
}
declare module 'nivo/lib/lib/colors/inherit.js' {
  declare module.exports: $Exports<'nivo/lib/lib/colors/inherit'>;
}
declare module 'nivo/lib/lib/colors/motion.js' {
  declare module.exports: $Exports<'nivo/lib/lib/colors/motion'>;
}
declare module 'nivo/lib/lib/colors/quantize.js' {
  declare module.exports: $Exports<'nivo/lib/lib/colors/quantize'>;
}
declare module 'nivo/lib/lib/defs.js' {
  declare module.exports: $Exports<'nivo/lib/lib/defs'>;
}
declare module 'nivo/lib/lib/hierarchy.js' {
  declare module.exports: $Exports<'nivo/lib/lib/hierarchy'>;
}
declare module 'nivo/lib/lib/interactivity/detect.js' {
  declare module.exports: $Exports<'nivo/lib/lib/interactivity/detect'>;
}
declare module 'nivo/lib/lib/interactivity/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/interactivity/index'>;
}
declare module 'nivo/lib/lib/noop.js' {
  declare module.exports: $Exports<'nivo/lib/lib/noop'>;
}
declare module 'nivo/lib/lib/polar/index.js' {
  declare module.exports: $Exports<'nivo/lib/lib/polar/index'>;
}
declare module 'nivo/lib/lib/polar/labels.js' {
  declare module.exports: $Exports<'nivo/lib/lib/polar/labels'>;
}
declare module 'nivo/lib/lib/polar/utils.js' {
  declare module.exports: $Exports<'nivo/lib/lib/polar/utils'>;
}
declare module 'nivo/lib/lib/propertiesConverters.js' {
  declare module.exports: $Exports<'nivo/lib/lib/propertiesConverters'>;
}
declare module 'nivo/lib/props/colors.js' {
  declare module.exports: $Exports<'nivo/lib/props/colors'>;
}
declare module 'nivo/lib/props/curve.js' {
  declare module.exports: $Exports<'nivo/lib/props/curve'>;
}
declare module 'nivo/lib/props/defs.js' {
  declare module.exports: $Exports<'nivo/lib/props/defs'>;
}
declare module 'nivo/lib/props/index.js' {
  declare module.exports: $Exports<'nivo/lib/props/index'>;
}
declare module 'nivo/lib/props/sankey.js' {
  declare module.exports: $Exports<'nivo/lib/props/sankey'>;
}
declare module 'nivo/lib/props/stack.js' {
  declare module.exports: $Exports<'nivo/lib/props/stack'>;
}
declare module 'nivo/lib/props/treeMap.js' {
  declare module.exports: $Exports<'nivo/lib/props/treeMap'>;
}
declare module 'nivo/scripts/generate-changelog.js' {
  declare module.exports: $Exports<'nivo/scripts/generate-changelog'>;
}
