// flow-typed signature: 849cb8d7a915edfb8f0ee315f1071c1a
// flow-typed version: <<STUB>>/react-images-upload_v^1.2.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-images-upload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-images-upload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-images-upload/compiled' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-images-upload/compiled.js' {
  declare module.exports: $Exports<'react-images-upload/compiled'>;
}
declare module 'react-images-upload/index' {
  declare module.exports: $Exports<'react-images-upload'>;
}
declare module 'react-images-upload/index.js' {
  declare module.exports: $Exports<'react-images-upload'>;
}
