// flow-typed signature: 5a904500bb53fd2ebf70fd5153e0117e
// flow-typed version: <<STUB>>/@nivo/bar_v^0.49.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/bar/cjs/nivo-bar' {
  declare module.exports: any;
}

declare module '@nivo/bar/umd/nivo-bar' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/bar/cjs/nivo-bar.js' {
  declare module.exports: $Exports<'@nivo/bar/cjs/nivo-bar'>;
}
declare module '@nivo/bar/index' {
  declare module.exports: $Exports<'@nivo/bar'>;
}
declare module '@nivo/bar/index.js' {
  declare module.exports: $Exports<'@nivo/bar'>;
}
declare module '@nivo/bar/umd/nivo-bar.js' {
  declare module.exports: $Exports<'@nivo/bar/umd/nivo-bar'>;
}
