// flow-typed signature: 88092fe9812304c1a5fdfe0d604c8c39
// flow-typed version: <<STUB>>/@nivo/line_v^0.49.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/line'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/line' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/line/cjs/nivo-line' {
  declare module.exports: any;
}

declare module '@nivo/line/umd/nivo-line' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/line/cjs/nivo-line.js' {
  declare module.exports: $Exports<'@nivo/line/cjs/nivo-line'>;
}
declare module '@nivo/line/index' {
  declare module.exports: $Exports<'@nivo/line'>;
}
declare module '@nivo/line/index.js' {
  declare module.exports: $Exports<'@nivo/line'>;
}
declare module '@nivo/line/umd/nivo-line.js' {
  declare module.exports: $Exports<'@nivo/line/umd/nivo-line'>;
}
